fagun-student:
 username: fagun.bhavsar@gmail.com
 password: Fagun@456
 description: a student user with no vocabulary assigned

fagun-site-admin:
  username: fagun@zinclearninglabs.com
  password: Fagun@456
  description: a site admin user

